var LogFactory=storage.LogFactory;
var StorageFactory=storage.StorageFactory;
var logf=new LogFactory();
var logger=logf.create();
var sf=new StorageFactory();
var s=sf.create();
a=s.init("a",0);
b=s.init("b",1);
c=s.init("c",2);
c=s.init("d",[]);
if(s.get("a")>5)s.set("d",[]);
s.set("a",s.get("a")+1);
s.set("b",s.get("b")+1);
s.set("c",s.get("c")+1);
s.append("d",s.get("d").length+1);
logger.log(s.get("a"));
logger.log(s.get("b"));
logger.log(s.get("c"));
logger.log(s.get("d"));
logger.log(s.toString());
logger.log(s.toJson());
if(s.get("a")>10)s.clear();
s.commit();
logger.flush();
