#!/bin/bash
PROTOCOL=http
HOST=skullquake.dedicated.co.za
PORT=80
HOST=localhost
PORT=8081
ENDPOINT=/kweexamples/src/graphing/api/
OUTFMT=json
URL=$PROTOCOL://$HOST:$PORT$ENDPOINT
#--------------------------------------------------------------------------------

#!/bin/bash
PROTOCOL=http
HOST=skullquake.dedicated.co.za
PORT=80
HOST=localhost
PORT=8081
ENDPOINT=/kweexamples/src/graphing/api/
URL=$PROTOCOL://$HOST:$PORT$ENDPOINT
#--------------------------------------------------------------------------------
curl\
	-X POST\
	-H "Content-Type: application/javascript"\
	"$URL?cmd=exec"\
	--output -\
	--data-binary @- << EOF

function(){
	var a=[];
	for(var i=0;i<32;i++)a.push(i);
	return a;
}
EOF
#--------------------------------------------------------------------------------
curl\
	-X POST\
	-H "Content-Type: application/javascript"\
	"$URL?cmd=exec"\
	--output -\
	--data-binary @- << EOF
function(){
	var ret;
	try{
		var storage;
		require(["lib/storage.js"],function(s){
			storage=s;
		});
		ret=storage.test();
	}catch(e){ret=e;};
	return ret;
}
EOF
#--------------------------------------------------------------------------------
