define([
	"module",
	"jquery",
	"render",
	"app",
	"text!frag/login.html",
	"text!frag/home.html"
],function(
	module,
	$,
	render,
	app,
	frag_login,
	frag_home
){
	var app={
		target:$("#out"),
		template:frag_login,
		error:null,
		login:function(usr,pas){
			this.data.usr=usr;
			this.data.pas=pas;
			$.ajax({
				method:"post",
				url:"./api/?"+$.param({"cmd":"login"}),
				contentType:"application/json; charset=utf-8",
				data:JSON.stringify({
					"usr":usr,
					"pas":pas
				}),
				success:function(r){
					if(r.error){
						this.error=r.error;
						render(this);
					}else{
						render({
							target:$("#out"),
							template:frag_home,
							logout:function(){
								this.data.usr="";
								this.data.pas="";
								this.error=null;
								render(this)
							}.bind(this),
							session:r,
							data:{}
						})
					}
				}.bind(this),
				error:function(e){
					alert(JSON.stringify(r));
				}.bind(this)
			}).then(function(a){
			});
		},
		data:{
			usr:"",
			pas:"",
		}
	}
	module.exports=app;
});

