define(["module"],function(module){
	module.exports={
		//main config settings
		enabled:true,
		cmdpath:"./cmd/",
		preprocessor:[
			"./mw/pre_decryptor.js",	//amd module preprocessors
			"./mw/pre0.js",			//...
			"./mw/pre1.js",			//...
			function(){},			//inline preprocessor
			function(){},			//...
			function(){},			//...
			function(){}			//...
		],
		postprocessor:[
			"./mw/post0.js",		//amd module postprocessors
			"./mw/post1.js",		//...
			"./mw/post_encryptor.js",	//...
			function(){},			//inline postprocessor
			function(){},			//...
			function(){},			//...
			function(){}			//...
		],
		//extra config settings
		debug:true,
		secret:"secret123"
	}
});
